[package]
name = "lexicon"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29", default-features = false, features = ["glow", "default_fonts"]}
egui_plot = "0.29.*"
pdf2image = "0.1.*"
serde = { version = "1.*", features = ["derive"] }
serde_json = "1.*"
